name: flutter_app
description: Berezka
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^3.1.0
  cached_network_image: ^1.1.1
  built_value: ^6.7.1
  rxdart: ^0.22.3
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  built_value_generator: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Averta CY
      fonts:
        - asset: fonts/Averta Cyrillic Regular.otf
        - asset: fonts/Averta Cyrillic SemiBold.otf
          weight: 500
        - asset: fonts/Averta Cyrillic Bold.otf
          weight: 700